# Adding theme
# theme: hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Splunk Tools
description: This page is to assist in building Splunk and Splunk SOAR apps related to the Splunk Conf talks.

# Google Analytics
google_analytics: G-V7NBSQFZ6G
